### ISSUE TITLE
bsod in win 11

### ISSUE THREAD

**Issue by generalmokka** [dvemon/data-ptr-comm#1]
it's bsod when loading on win 11 any fix for it or even any hint to fix it ?

**Comment by hcmzah** [comment]
do you have an intel or an amd cpu?

**Comment by generalmokka** [comment]
amd

**Comment by hcmzah** [comment]
you need to disable retpoline

run this in cmd admin priv and then restart your machine

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v FeatureSettingsOverride /t REG_DWORD /d 3 /f

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v FeatureSettingsOverrideMask /t REG_DWORD /d 3 /f

**Comment by generalmokka** [comment]
worked now thank u.
if cpu is intel it's usa this same reg or have other func need edit ?

**Comment by hcmzah** [comment]
the same but you might have to change with other window versions

**Comment by MrKouhx** [comment]
when read write base 15min later get bsod (alot of read)
what here issue?
