### ISSUE TITLE
1909 and other versions

### ISSUE THREAD

**Issue by nuss31** [dvemon/data-ptr-comm#3]
So i tried to use it on my main system win 10 20h2
And then on a vm thats on 1909 and it cant find the ptr
also my friends tried it on 20h2 aswell and there the ptr dosent get found aswell what could the problem be?

**Comment by hcmzah** [comment]
What CPU do you have?

**Comment by nuss31** [comment]
Amd but it works on my main system but not on the vm or on any of my friend pcs cause the ptr cant get found i tried finding the sig in ida on the 1909 driver but i cant find it

**Comment by hcmzah** [comment]
Did you try this?
#1

**Comment by nuss31** [comment]
i did

**Comment by hcmzah** [comment]
make sure these are set to false, otherwise you'll have to debug yourself

BTIKernelRetpolineEnabled : True
BTIKernelImportOptimizationEnabled  : True

**Comment by nuss31** [comment]
then i guess i need to debug more
